name: Secure Facebook Live Stream (RTMPS)

on:
  workflow_dispatch:

jobs:
  stream:
    runs-on: ubuntu-latest
    steps:
      - name: Set up FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Stream to Facebook using RTMPS
        run: |
          ffmpeg -re \
          -i "http://mo3ad.xyz/GpfGbMNfzW/XJFgkQnpXd/8" \
          -c:v libx264 -preset medium -maxrate 2500k -bufsize 5000k \
          -vf "scale=1280:-1" -g 60 -c:a aac -b:a 128k \
          -strict experimental \
          -f flv "rtmps://live-api-s.facebook.com:443/rtmp/FB-122129498810499805-0-Abwnz5xRhkpiH6gs" \
          -timeout 5000000 -reconnect 1 -reconnect_streamed 1 -reconnect_delay_max 5
